# Generated by Django 6.0.4 on 2026-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФІО Клієнта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photos/', verbose_name='Фото клієнта')),
                ('sub_type', models.CharField(choices=[('Разовий', 'Разовий'), ('Місяць', 'Місяць'), ('Рік', 'Рік')], max_length=20, verbose_name='Тип абонемента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата запису')),
            ],
        ),
    ]
