# Generated by Django 6.0.4 on 2026-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_trainer_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_photos/', verbose_name='Фото тренера'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='Рейтинг (Зірки)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name="Прізвище та ім'я"),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/', verbose_name='Фото клієнта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sub_type',
            field=models.CharField(choices=[('day', 'На день'), ('month', 'Місяць'), ('year', 'Рік')], default='month', max_length=10, verbose_name='Тип абонемента'),
        ),
    ]
